"""Add department and other models

Revision ID: 0b3ca239f839
Revises: 
Create Date: 2026-05-14 16:19:36.317290

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0b3ca239f839'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('system_settings')
    op.alter_column('audit_logs', 'trace_id',
               existing_type=sa.VARCHAR(length=12),
               comment='请求追踪 ID',
               existing_nullable=True)
    op.alter_column('audit_logs', 'severity',
               existing_type=sa.VARCHAR(length=10),
               comment='日志级别: INFO/WARN/ERROR',
               existing_nullable=False,
               existing_server_default=sa.text("'INFO'::character varying"))
    op.alter_column('audit_logs', 'user_agent',
               existing_type=sa.VARCHAR(length=500),
               comment='客户端 User-Agent',
               existing_nullable=True)
    op.alter_column('audit_logs', 'duration_ms',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='请求耗时（毫秒）',
               existing_nullable=True)
    op.drop_index(op.f('ix_audit_logs_severity_created'), table_name='audit_logs')
    op.create_index('ix_conv_user_updated', 'conversations', ['user_id', 'updated_at'], unique=False)
    op.create_index('ix_msg_conv_created', 'messages', ['conversation_id', 'created_at'], unique=False)
    op.add_column('users', sa.Column('department_id', sa.String(length=36), nullable=True))
    op.create_index(op.f('ix_users_department_id'), 'users', ['department_id'], unique=False)
    op.create_foreign_key(None, 'users', 'departments', ['department_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_index(op.f('ix_users_department_id'), table_name='users')
    op.drop_column('users', 'department_id')
    op.drop_index('ix_msg_conv_created', table_name='messages')
    op.drop_index('ix_conv_user_updated', table_name='conversations')
    op.create_index(op.f('ix_audit_logs_severity_created'), 'audit_logs', ['severity', 'created_at'], unique=False)
    op.alter_column('audit_logs', 'duration_ms',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='请求耗时（毫秒）',
               existing_nullable=True)
    op.alter_column('audit_logs', 'user_agent',
               existing_type=sa.VARCHAR(length=500),
               comment=None,
               existing_comment='客户端 User-Agent',
               existing_nullable=True)
    op.alter_column('audit_logs', 'severity',
               existing_type=sa.VARCHAR(length=10),
               comment=None,
               existing_comment='日志级别: INFO/WARN/ERROR',
               existing_nullable=False,
               existing_server_default=sa.text("'INFO'::character varying"))
    op.alter_column('audit_logs', 'trace_id',
               existing_type=sa.VARCHAR(length=12),
               comment=None,
               existing_comment='请求追踪 ID',
               existing_nullable=True)
    op.create_table('system_settings',
    sa.Column('key', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('value', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('description', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('key', name=op.f('system_settings_pkey'))
    )
    # ### end Alembic commands ###
